### ISSUE TITLE
upload_stream is incompatible the requests library >= 2.9.0 (files larger that ~15Kb)

### ISSUE THREAD

**Issue by samkuehn** [box/box-python-sdk#102] opened 2015-12-28 19:54 UTC
Seems to timeout and then throw exception:
ConnectionError: ('Connection aborted.', BadStatusLine("''", ))

Bugfix 1 and 2 seem to be the likely culprits:
http://docs.python-requests.org/en/latest/community/updates/#id2

I believe it MAY be related to this commit but I am not sure:
https://github.com/kennethreitz/requests/commit/5397ef71b37ebe1fdf8af95a9a3b561baffe9dd8

**Comment by samkuehn** [comment] 2015-12-28 19:55
Downgrading to requests==2.8.1 fixes this issue.

**Comment by jmoldow** [comment] 2015-12-28 21:04
Just checking, is this also a problem in requests==2.9.1? The release notes say "Resolve regression introduced in 2.9.0 that made it impossible to send binary strings as bodies in Python 3." Don't know if that's the same problem that you've discovered, or a different one.

Thanks for finding and reporting this!

**Comment by samkuehn** [comment] 2015-12-28 21:07
Yes, this is a problem in requests==2.9.1 as well (I am using python 2.7).

**Comment by Jeff-Meadows** [comment] 2016-01-04 22:21
I guess this is a duplicate of https://github.com/sigmavirus24/requests-toolbelt/issues/117

Please upgrade requests-toolbelt >= 0.5.0 if you upgrade requests >= 2.9.0

**Closed by Jeff-Meadows** 2016-01-04 22:21 UTC

**Comment by chrismcmacken** [comment] 2017-03-07 18:36
I am still running into this issue with versions of requests and requests-toolbelt above the ones posted above. 

requests (2.13.0) 
requests-toolbelt (0.7.0)
