### ISSUE TITLE
_RSAPrivateKey' object has no attribute 'sign'

### ISSUE THREAD

**Issue by peternye** [box/box-python-sdk#610] opened 2021-07-27 17:35 UTC
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Versions Used
Python SDK: 
Python: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment] 2021-07-28 15:55
Duplicate of #611.

**Closed by mwwoda** 2021-07-28 15:55 UTC
Labels: bug
