### ISSUE TITLE
How can I permanently delete trashed files of another user's account as an Admin?

### ISSUE THREAD

**Issue by StefanMarchand** [box/box-python-sdk#540] opened 2020-09-15 20:36 UTC
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I'm trying to delete all trashed files that are over 90 days old for each user in an account. However when I run the permanently_delete_item() function I get an 404 not found or 403 insufficient permissions. How can I permanently delete trashed files of another user's account as an Admin?
### Screenshots
trashed_items = user_client.trash().get_items(limit=5000, fields=('trashed_at', 'name'))
        #try:
        if trashed_items is not None:
            for trashed_item in trashed_items:
                trashedDate = trashed_item.trashed_at[0:10]
                date_time_obj = datetime.strptime(trashedDate, '%Y-%m-%d')
                time_between_insertion = todayDate - date_time_obj
                if time_between_insertion.days>90:
                    writer.writerow([userTarget.login, trashed_item.name, trashed_item.trashed_at, userTarget.id, trashed_item.id])
                    file_to_delete = user_client.file(file_id=trashed_item.id)
                    client.trash().permanently_delete_item(file_to_delete)
                    #put delete logic here
                    deleteCnt = deleteCnt + 1
                del trashed_item   
            
        # except:
        #     writerErr.writerow([user.login, user.id])
        print('Deleted {0} items.'.format(deleteCnt))    
        del trashed_items

### Versions Used
Python SDK: 
Python: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by StefanMarchand** [comment] 2020-09-15 22:21
A similar unsolved issue is discussed here: 
https://support.box.com/hc/en-us/community/posts/360049192253-Box-API-Delete-Trash-not-working-

**Comment by sujaygarlanka** [comment] 2020-09-28 15:19
Duplicate of #547

**Closed by sujaygarlanka** 2020-09-28 15:19 UTC
Labels: question
