### ISSUE TITLE
Add file versions functionality

### ISSUE THREAD

**Issue by jmoldow** [box/box-python-sdk#39] opened 2015-04-03 04:05 UTC
The SDK should be able to get the versions of a file, download a specific version of a file, and perform other file version operations.

Will require a `FileVersion` class. (question: what should this be a subclass of? BaseObject? Item? File?)

https://developers.box.com/docs/#files-download-a-file
https://developers.box.com/docs/#files-view-versions-of-a-file
https://developers.box.com/docs/#files-download-old-version
https://developers.box.com/docs/#files-promote-old-version
https://developers.box.com/docs/#files-delete-version

**Comment by Jeff-Meadows** [comment] 2016-03-28 23:27
Duplicate of #43

**Closed by Jeff-Meadows** 2016-03-28 23:27 UTC
Labels: enhancement
