### ISSUE TITLE
Uncaught ValueError Exception in session renewal code

### ISSUE THREAD

**Issue by morr0350** [box/box-python-sdk#220] opened 2017-08-07 18:06 UTC
Occasionally we are getting an uncaught exception from the Box Python SDK when it tries to unpack the return values from refreshing an OAuth token – there is an unused response value (with an underscore placeholder) that is not being supplied by the called` _oauth.refresh` method.  It seems to happen most commonly on the file endpoint when requesting text extraction, but I can’t really explain why that would be related to session renewal.   This ends up bubbling up as a nasty 500 error for our end users since it cannot be recovered, so it would be great if a true `BoxException ` could be caught by this, rather than throwing an uncaught `ValueError`.   Stacktrace:
 
```
[2017-08-07 15:43:09,508] ERROR django.request - Internal Server Error: 
Traceback (most recent call last):
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/xxxx/Dev/xxxx/xxxx/xxxx/decorators.py", line 96, in check_membership
    return func(*args, **kwargs)
  File "/home/xxxx/Dev/xxxx/xxxx/xxxx/views.py", line 524, in get
    return super(DocumentDiffView, self).get(request, *args, **kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/xxxx/Dev/xxxx/xxxx/xxxx/views.py", line 542, in get_context_data
    source_txt = self.box.get_file_text(source.doc_file.name).decode('utf8', errors='ignore')
  File "/home/xxxx/Dev/xxxx/xxxx/xxxx/storage.py", line 410, in get_file_text
    conversion_url = self._get_file_conversion_url(uuid, '[extracted_text]')
  File "/home/xxxx/Dev/xxxx/xxxx/xxxx/storage.py", line 423, in _get_file_conversion_url
    headers={'X-Rep-Hints': file_representation_code}
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/util/api_call_decorator.py", line 56, in call
    response = self._func_that_makes_an_api_call(instance, *args, **kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/client/client.py", line 370, in make_request
    return self._session.request(method, url, **kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 510, in request
    response = self._prepare_and_send_request(method, url, **kwargs)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 350, in _prepare_and_send_request
    **kwargs
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 434, in _make_request
    **kwargs
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 232, in _retry_request_if_necessary
    self._renew_session(network_response.access_token_used)
  File "/home/xxxx/.virtualenvs/xxxx/local/lib/python2.7/site-packages/boxsdk/session/box_session.py", line 196, in _renew_session
    new_access_token, _ = self._oauth.refresh(access_token_used)
ValueError: too many values to unpack
```

**Comment by jmoldow** [comment] 2017-08-07 20:53
This is a duplicate of #197

**Closed by jmoldow** 2017-08-07 20:53 UTC

**Comment by morr0350** [comment] 2017-08-07 21:36
Thanks for porting to 1.5.4
