### ISSUE TITLE
Python SDK Error

### ISSUE THREAD

**Issue by WillBGE** [box/box-python-sdk#514] opened 2020-06-12 15:32 UTC
Submitting per Tatyana @ Box (Case 2182873):

User Dani.Pinkovich@ge.com is getting

error: Request "GET https://api.box.com/2.0/folders/0/items" failed with ConnectionError exception:
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.box.com', port=443):
Max retries exceeded with url: /2.0/folders/0/items?offset=0
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001623BC88988>:
Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"))

when trying to view folder items. Dani is making a GET call to https://api.box.com/2.0/folders/0/items.
He is authenticating as Service.Ultranet@ge.com. Dani is using the Python SDK, version 2.8.0. His app's details are below:

app name: GEHC_Ultranet_Ingestion
client ID: qxjk7o64obs5xqlyhio6b7hkbsw90gel

When using postman, we are able to get the folder information on and off network.

Last email from Tatyana:

Thanks, Dani.

When querying within a few minutes of that timestamp for your app's activity, these are the IP addresses that are being used:

194.9.245.34   
104.129.196.179   
208.49.203.14   
3.230.237.143

However, when I looked at any GET calls made from any of these IPs, I get no results. 

Since you can make the call successfully in Postman, I agree that this is definitely an issue with the SDK.

**Comment by Jeff-Meadows** [comment] 2020-06-12 15:45
This almost certainly is a network configuration issue. `[Errno 11001] getaddrinfo failed` indicates that the process isn't able to resolve the address of `api.box.com`. This is common when the code is being run on a machine where internet access is managed by a proxy. If it works in postman, that's probably because the browser from which it's being run (Chrome) is configured for the proxy.

I'm not sure if we have any tutorials for configuring Python for proxy settings.

**Comment by PJSimon** [comment] 2020-06-12 21:23
@WillBGE was @Jeff-Meadows's comment helpful?
Perhaps [this documentation](https://github.com/box/box-python-sdk/blob/master/docs/usage/configuration.md) can help you configure proxy settings for your Python project.

**Comment by WillBGE** [comment] 2020-06-14 19:59
Hi guys,

I’ve passed this info along to my user.  Thanks!

Thank you,
Will


Will Belcher
Application Operations Engineer
Corporate Coretech & Cyber, Digital Workplace
E: William.Belcher@ge.com<mailto:William.Belcher@ge.com>  P: +1 401 451-5379

75 Fountain Street Suite 300 | Providence, RI 02902 USA
General Electric Company

**Comment by WillBGE** [comment] 2020-06-15 13:54
Hi guys,

My user is still getting the 443 error after reconfiguring the proxy.  He is able to get an access token but unable to process any folder transactions.  I had our network team check the firewall, and api.box.com is whitelisted, so outbound traffic is not being blocked.  Any other suggestions?

Thank you,
Will


Will Belcher
Application Operations Engineer
Corporate Coretech & Cyber, Digital Workplace
E: William.Belcher@ge.com<mailto:William.Belcher@ge.com>  P: +1 401 451-5379

75 Fountain Street Suite 300 | Providence, RI 02902 USA
General Electric Company

From: Belcher, William (GE CoreTech & Cyber)
Sent: Sunday, June 14, 2020 4:00 PM
To: box/box-python-sdk <reply@reply.github.com>; box/box-python-sdk <box-python-sdk@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: EXT: Re: [box/box-python-sdk] Python SDK Error (#514)

Hi guys,

I’ve passed this info along to my user.  Thanks!

Thank you,
Will


Will Belcher
Application Operations Engineer
Corporate Coretech & Cyber, Digital Workplace
E: William.Belcher@ge.com<mailto:William.Belcher@ge.com>  P: +1 401 451-5379

75 Fountain Street Suite 300 | Providence, RI 02902 USA
General Electric Company

**Comment by yossibatash** [comment] 2020-06-17 06:17
Hi guys, 
I am also getting the same error, is there a workaround or a stable version?
Best
Yossi

**Comment by sujaygarlanka** [comment] 2020-06-17 23:10
@yossibatash Are you also running the SDK behind a proxy and if so, what type of proxy is it?

**Comment by sujaygarlanka** [comment] 2020-06-17 23:11
@WillBGE What type of proxy is being used (i.e. http, https, socks)?

**Comment by sujaygarlanka** [comment] 2020-06-18 16:41
@WillBGE I would also try using running a curl command like the one below in your environment. If it works, then we know the issue is more likely related to the SDK rather than the environment.

```
curl -X GET https://api.box.com/2.0/files/12345 \
     -H 'Authorization: Bearer <ACCESS_TOKEN>'

**Comment by danipinkovich** [comment] 2020-06-18 16:52
C:>curl -X GET https://api.box.com/2.0/files/12345 -H 'Authorization: Bearer 0003AGCybo6d7xSPjtBYzpQmf2F5'
curl: (52) Empty reply from server
<html><head><title>400 Bad Request</title></head>
<body><h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br></p>
</body></html>
curl: (56) Recv failure: Connection was reset

**Comment by WillBGE** [comment] 2020-06-18 17:27
Dani, use the real folder ID and confirm the outcome?

Thank you,
Will


Will Belcher
Application Operations Engineer
Corporate Coretech & Cyber, Digital Workplace
E: William.Belcher@ge.com<mailto:William.Belcher@ge.com>  P: +1 401 451-5379

75 Fountain Street Suite 300 | Providence, RI 02902 USA
General Electric Company

**Comment by danipinkovich** [comment] 2020-06-19 11:23
This is one of the folders I see as the API user:

https://ge.ent.box.com/folder/115260218908

Is this the same url I should try with curl?

Best regards,
Dani

**Comment by WillBGE** [comment] 2020-06-19 12:23
Do

curl -X GET https://api.box.com/2.0/folders/115260218908 -H 'Authorization: Bearer <Insert Token>'

Thank you,
Will


Will Belcher
Application Operations Engineer
Corporate Coretech & Cyber, Digital Workplace
E: William.Belcher@ge.com<mailto:William.Belcher@ge.com>  P: +1 401 451-5379

75 Fountain Street Suite 300 | Providence, RI 02902 USA
General Electric Company

**Comment by danipinkovich** [comment] 2020-06-19 12:48
{'access_token': '0003ZguZ9Ip8C0Iw3mujIsQnJc0l', 'token_type': 'Bearer', 'expires_in': 7199}

C:\>curl -X GET https://api.box.com/2.0/folders/115260218908 -H 'Authorization: Bearer 0003ZguZ9Ip8C0Iw3mujIsQnJc0l'
curl: (52) Empty reply from server
<html><head><title>400 Bad Request</title></head>
<body><h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br></p>
</body></html>
curl: (56) Recv failure: Connection was reset



Best regards,
Dani

**Comment by sujaygarlanka** [comment] 2020-06-19 14:35
@danipinkovich @WillBGE Even the curl doesn’t seem to be working and is throwing a connection reset error. So it seems like it’s something to do with general environment more than the SDK.

**Comment by PJSimon** [comment] 2020-06-27 04:53
HI @danipinkovich @WillBGE ,

It sounds like this issue is with your environment and not with the SDK.  Any update from your end?  I'm going to assume that we can close this Issue, but if you are still having issues, please just re-open it and we'll go from there!

Thanks,

Patrick

**Closed by PJSimon** 2020-06-27 04:53 UTC
Labels: bug

**Comment by zKarp** [comment] 2020-07-24 19:48
@WillBGE Wanted to note this is all public. Might want to redact some info.

**Comment by yossibatash** [comment] 2020-07-25 11:35
Hi @sujaygarlanka, I have managed to isolate the problem, when I am turning off my VPN (Palo alto global protect) I am not experiencing this issue, I asked my DevOps team to enable this type of request in the firewall but they haven't done it yet so I can't really say that this issue been resolved
Hope that helping
